apiVersion: v1
kind: Service
metadata:
  name: voting-app
  namespace: namespace-workflow-1719986225002
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: voting-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000